### PR TITLE
Attempt to fix build

### LINKED ISSUE #108: multiple typescript errors with version 2.11.0
I am new to react-dropzone-uploader. I `yarn add react-dropzone-uploader` in my application and followed [quickstart guide](https://react-dropzone-uploader.js.org/docs/quick-start). I'm getting a number of typescript errors:

```
***/node_modules/react-dropzone-uploader/dist/utils.ts
TypeScript error in /***/node_modules/react-dropzone-uploader/dist/utils.ts(104,7):
Type 'FileList' is not assignable to type 'null'.  TS2322

    102 |     // NOTE: Only the 'drop' event has access to DataTransfer.files, otherwise it will always be empty
    103 |     if ('files' in dt && dt.files.length) {
  > 104 |       items = dt.files
        |       ^
    105 |     } else if (dt.items && dt.items.length) {
    106 |       items = dt.items
    107 |     }
```

Here are relevant parts of package.json:

```
"dependencies": {
     ...
     "react": "^16.13.1",
     "react-dom": "^16.13.1",
     "react-dropzone-uploader": "^2.11.0",
     ...
     "typescript": "~3.7.2",
}
```

This is my tsconfig.json file:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "baseUrl": "src",
    "rootDir": "./",
    "checkJs": false,
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "build",
    "dist",
    "src/**/*.js",
    "src/**/*.jsx"
  ]
}
```

Thank you for this library and for your diligent support.

### LINKED ISSUE #114: error with typescript
I don't know why it's giving me this error...
can someone help?

TypeScript error in C:/Users/User/Desktop/dev/node_modules/react-dropzone-uploader/dist/Dropzone.tsx(635,7):
Type 'Element[]' is not assignable to type 'null'.  TS2322
```

    633 |     let previews = null
    634 |     if (PreviewComponent !== null) {
  > 635 |       previews = files.map(f => {
```

and :

TypeScript error in C:/Users/User/Desktop/dev/zidyia-frontend/node_modules/react-dropzone-uploader/dist/utils.ts(104,7):
Type 'FileList' is not assignable to type 'null'.  TS2322
```

    102 |     // NOTE: Only the 'drop' event has access to DataTransfer.files, otherwise it will always be empty        
    103 |     if ('files' in dt && dt.files.length) {
  > 104 |       items = dt.files
        |       ^
```

### LINKED ISSUE #179: Unable to compile with Typescript 4.5.4
I recently upgraded the version of typescript in a react project to version 4.5.4.
When I did this I got an compile error reported in react-dropzone-uploader.
I am using version 2.11.0 of react-dropzone-uploader
In Typescript 4.4 the typing of the catch variable was changed to be "unknown" from "any". As a result the error was reported. 
The error I get is:
`node_modules/react-dropzone-uploader/dist/Dropzone.tsx:504:44 - error TS2571: Object is of type 'unknown'.
`
The code in Dropzone.tsx is:
```
  uploadFile = async (fileWithMeta: IFileWithMeta) => {
    const { getUploadParams } = this.props
    if (!getUploadParams) return
    let params: IUploadParams | null = null
    try {
      params = await getUploadParams(fileWithMeta)
    } catch (e) {
      console.error('Error Upload Params', e.stack)
    }
    if (params === null) return
    const { url, method = 'POST', body, fields = {}, headers = {}, meta: extraMeta = {} } = params
    delete extraMeta.status

```
The problem is the catch variable "e" is now typed as "unknown" and so it is an error to attempt to access a member of "unknown"

Typescript has introduced an option "useUnknownInCatchVariables" which when set to "false" will allow the code to compile and that is how I am getting around the problem.

A suggestion has been made to me that I need to wrap my call to react-dropzone-uploader in a try-catch to solve my problem.
That will not solve my issue. My issue is I cannot compile my project. 
The person making the suggestion seemed to believe that the try-catch in question was in my code and that I should fix my code.

The problem lies in the Dropzone.tsx file of react-dropzone_uploader. And the fix is very easy:
```
    try {
      params = await getUploadParams(fileWithMeta)
    } catch (e) {
      console.error('Error Upload Params', (e as any).stack)
    }

```

### PR DESCRIPTION
**Pull request by wweaver**
I attempted to update this to fix the typescript errors.

This is upgrading webpack and typescript, fixing the new typescript error and hopefully more properly generate the .d.ts files.

Fixes: https://github.com/fortana-co/react-dropzone-uploader/issues/179
Fixes: https://github.com/fortana-co/react-dropzone-uploader/issues/108
Fixes: https://github.com/fortana-co/react-dropzone-uploader/issues/114

https://www.npmjs.com/package/@cruisecritic/react-dropzone-uploader

### CODE REVIEW

**Comment by bibek-magar** [comment]
ANy alternative method to fix.. before merge?

**Comment by wweaver** [comment]
> ANy alternative method to fix.. before merge?

It seems someone posted https://github.com/fortana-co/react-dropzone-uploader/pull/202 which does a much smaller change. Haven't tried it to know if it works.

**Comment by wweaver** [comment]
Cleaning up my pull request. I've moved my code away from react-dropzone-uploader since it's not maintained.
